### ISSUE TITLE
How to use stored procedures?

### ISSUE THREAD

**Issue by Blira** [featurist/sworm#55]
I know the documentation states this: 
![Screenshot from 2020-04-13 18-05-25](https://user-images.githubusercontent.com/43551066/79161213-7727c580-7db1-11ea-8c33-ed5ca7763eb1.png)

But if i use 

 `sworm.query('MY_PROCEDURE');`

I get the error: 

`sworm MY_PROCEDURE {} [Error: ORA-00900: invalid SQL statement] { errorNum: 900, offset: 0 }`

I also tried 
`sworm.query('BEGIN MY_PROCEDURE; END;');`

But got

`sworm BEGIN MY_PROCEDURE; END; {} TypeError: Cannot read property 'getRows' of undefined
    at fetchRows (/home/myUser/Services/myService/node_modules/sworm/oracleDriver.js:62:28)
    at /home/myUser/Services/myService/node_modules/sworm/oracleDriver.js:75:16`

And tried 

`sworm.query('EXEC MY_PROCEDURE')`

but got 

`[Error: ORA-00900: invalid SQL statement] { errorNum: 900, offset: 0 }`

Every other query seems to be working fine. Updates, inserts, selects...

How can I use procedures?

**Comment by Blira** [comment]
Managed to make it work by using: 

`sworm.statement('BEGIN MY_PROCEDURE; END;');`
